name: Run Jupyter Notebook

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install notebook
          pip install nbconvert
          pip install numpy
          pip install pandas
          pip install imblearn
          pip install seaborn
          pip install matplotlib
          pip install scikit-learn
          pip install collection
          
      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute Credit_Card_Fraud_Detection.ipynb --output executed_notebook.ipynb
